# Generated by Django 4.1.7 on 2023-03-08 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('breed', models.CharField(max_length=100, verbose_name='Breed')),
                ('deceased_date', models.DateField(blank=True, null=True, verbose_name='Deceased date')),
                ('owners', models.ManyToManyField(related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
