# Generated by Django 4.1.7 on 2023-03-08 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="owners",
            field=models.ManyToManyField(
                related_name="pets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
